src/main/java/at/qe/sepm/skeleton/model/Attendance.java
package at.qe.sepm.skeleton.model;

import java.util.UUID;
import java.util.Calendar;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.domain.Persistable;

/**
 * Entity representing attendances of children on certain days.
 * 
 */
@Entity
public class Attendance implements Persistable<String> {

	private static final long serialVersionUID = 1L;

	@Id
	private final String id;

	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Calendar creationDate;

	@Temporal(TemporalType.TIMESTAMP)
	private Calendar arrivalTime;

	@Temporal(TemporalType.TIMESTAMP)
	private Calendar departureTime;

	@ManyToOne(optional = false)
	@JoinColumn(name = "DAY_PLAN_DATE")
	private DayPlan dayPlan;

	@ManyToOne(optional = false)
	@JoinColumn(name = "CHILD_ID")
	private Child child;

	@ManyToOne
	@JoinColumn(name = "LUNCH_ID")
	private Lunch lunch;

	@ManyToOne
	@JoinColumn(name = "PERSON_ID")
	private Person pickUpPerson;

	@Column
	private boolean attending;

	public Attendance() {
		this.id = UUID.randomUUID().toString();
		attending = true;
	}

	public Attendance(DayPlan dayPlan, Child child) {
		this();
		this.dayPlan = dayPlan;
		this.child = child;
	}

	@Override
	public String getId() {
		return id;
	}

	@Override
	public boolean isNew() {
		return creationDate == null;
	}

	public Calendar getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Calendar creationDate) {
		this.creationDate = creationDate;
	}

	public Calendar getArrivalTime() {
		return arrivalTime;
	}

	public void setArrivalTime(Calendar arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	public Calendar getDepartureTime() {
		return departureTime;
	}

	public void setDepartureTime(Calendar departureTime) {
		this.departureTime = departureTime;
	}

	public DayPlan getDayPlan() {
		return dayPlan;
	}

	public void setDayPlan(DayPlan dayPlan) {
		this.dayPlan = dayPlan;
	}

	public Child getChild() {
		return child;
	}

	public void setChild(Child child) {
		this.child = child;
	}

	public Lunch getLunch() {
		return lunch;
	}

	public void setLunch(Lunch lunch) {
		this.lunch = lunch;
	}

	public Person getPickUpPerson() {
		return pickUpPerson;
	}

	public void setPickUpPerson(Person pickUpPerson) {
		this.pickUpPerson = pickUpPerson;
	}

	public boolean isAttending() {
		return attending;
	}

	public void setAttending(boolean attending) {
		this.attending = attending;
	}

	@Override
	public int hashCode() {
		int hash = 7;
		hash = 59 * hash + Objects.hashCode(this.getId());
		return hash;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Attendance)) {
			return false;
		}
		final Attendance other = (Attendance) obj;
		if (!Objects.equals(this.getId(), other.getId())) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "at.qe.sepm.skeleton.model.Attendance[ id='" + this.getId() + "']";
	}

}

src/main/java/at/qe/sepm/skeleton/model/MonthPlan.java
package at.qe.sepm.skeleton.model;

import javax.persistence.Entity;
import javax.persistence.Id;

import org.springframework.data.domain.Persistable;

/**
 * Model format for data of a certain month.
 *
 */
@Entity
public class MonthPlan implements Persistable<String> {
    
    private static final long serialVersionUID = 1L;
    
    @Id
    public int monthId;
    public String month;
    public int ovrOccupancy;
    public int avrOccupancy;
    public int open;

    public MonthPlan() {
    }
    
    public MonthPlan(int monthId, String month, int ovrOccupancy, int avrOccupancy, int open) {
        this.monthId = monthId;
        this.month = month;
        this.ovrOccupancy = ovrOccupancy;
        this.avrOccupancy = avrOccupancy;
        this.open = open;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public int getOvrOccupancy() {
        return ovrOccupancy;
    }

    public void setOvrOccupancy(int ovrOccupancy) {
        this.ovrOccupancy = ovrOccupancy;
    }

    public int getAvrOccupancy() {
        return avrOccupancy;
    }

    public void setAvrOccupancy(int avrOccupancy) {
        this.avrOccupancy = avrOccupancy;
    }

    public int getOpen() {
        return open;
    }

    public void setOpen(int open) {
        this.open = open;
    }

    @Override
    public String getId() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    @Override
    public boolean isNew() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    public int getMonthId() {
        return monthId;
    }
    
    public void setMonthId(int monthId) {
        this.monthId = monthId;
    }

}

src/main/java/at/qe/sepm/skeleton/ui/beans/LunchRegistrationBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.Attendance;
import at.qe.sepm.skeleton.model.Child;
import at.qe.sepm.skeleton.model.DayPlan;
import at.qe.sepm.skeleton.model.Lunch;
import at.qe.sepm.skeleton.services.AttendanceService;
import at.qe.sepm.skeleton.services.ChildService;
import at.qe.sepm.skeleton.services.DayPlanService;
import at.qe.sepm.skeleton.services.LunchService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.util.*;

/**
 * Lunch registration bean to retrieve and modify registrations for next week's lunch.
 * Used by parents.
 */
@Component
@Scope("view")
public class LunchRegistrationBean {

    @Autowired
    DayPlanService dayPlanService;
    
    @Autowired
    LunchService lunchService;
    
    @Autowired
    ChildService childService;
    
    @Autowired
    AttendanceService attendanceService;
    
    @Autowired
    SessionInfoBean sessionInfoBean;

    private Collection<DayPlan> nextWeek; //week open for registration
    
    private String lunch;
    
    private Collection<String> attendances;
    
    private DayPlan dayPlan;

    /**
     * get DayPlans and corresponding lunches for the next week.
     *
     */
    @PostConstruct
    public void init() {
        Calendar c = Calendar.getInstance();
        if(c.after(dayPlanService.loadCurrentLunchDeadline(c))) { //reached deadline, load the week after that
            c.add(Calendar.DATE, 7);
        }
        int currentDay = c.get(Calendar.DAY_OF_WEEK); //Sunday = 1

        Calendar from = Calendar.getInstance();
        c.add(Calendar.DATE, 9 - currentDay); //next Monday
        from.setTimeInMillis(c.getTimeInMillis());

        Calendar to = Calendar.getInstance();
        c.add(Calendar.DATE, 6); //next Sunday
        to.setTimeInMillis(c.getTimeInMillis());

        nextWeek = dayPlanService.loadDayPlansInTimeSpan(from, to);
        List<DayPlan> nextWeekClone = new LinkedList<>(nextWeek);

        //add days in which the user has at least one child registered
        for(DayPlan day: nextWeekClone) {
            Set<Attendance> intersection = new HashSet<>(day.getAttendances());
            Collection<Attendance> usersChildren = attendanceService.loadAttendancesOfChildrenByParentFromDate(sessionInfoBean.getCurrentUser(), day.getDayDate());
            intersection.retainAll(usersChildren);
            if (intersection.isEmpty()) {
                nextWeek.remove(day);
            }
        }
    }

    /**
     * Register lunch registrations for user's children on specified days.
     *
     */
    public void saveRegistration() {
        //get Child objects
        List<Attendance> attendanceObjects = new LinkedList<>();
        for (String attendanceId : attendances) {
            attendanceObjects.add(attendanceService.loadAttendance(attendanceId));
        }

        //delete if they were registered for other lunches and add to new one
        Lunch lunchObject = lunchService.loadLunch(lunch);
        for (Lunch l : dayPlan.getLunches()) {
            l.getConsumers().removeAll(attendanceObjects);
            lunchService.saveLunch(l);
        }

        //add new registrations
        lunchObject.getConsumers().addAll(attendanceObjects);
        lunchService.saveLunch(lunchObject);
        for(Attendance a : attendanceObjects) {
            a.setLunch(lunchObject);
            attendanceService.saveAttendance(a);
        }
        init();
    }

    /**
     * Delete all lunch registrations for user's children on specified day.
     *
     */
    public void deleteRegistration() {
        Collection<Child> parentsChildren = childService.loadChildrenByParent(sessionInfoBean.getCurrentUser());
        for (Lunch lunch : this.dayPlan.getLunches()) {
            for(Attendance attendance : lunch.getConsumers()) {
                if(parentsChildren.contains(attendance.getChild())) {
                    attendance.setLunch(null);
                    attendanceService.saveAttendance(attendance);
                    lunch.removeConsumer(attendance);
                    lunchService.saveLunch(lunch);
                }
            }
        }
    }

    /**
     * Finds all registered children of a parent for the in
     * {@link LunchRegistrationBean} saved day.
     *
     * @return Collection of parents' children that can be registered for lunch
     */
    public Collection<Attendance> getPossibleChildren() {
        Collection<Attendance> possibleAttendances = new LinkedList<>();
        for(Attendance a: dayPlan.getAttendances()) {
            if(childService.loadChildrenByParent(sessionInfoBean.getCurrentUser()).contains(a.getChild()))     //child is registered for today and user is parent
                possibleAttendances.add(a);
        }
        return possibleAttendances;
    }

    /**
     * Get children of current user that are registered for given lunch.
     *
     * @param lunch
     *            for which children are wanted
     * @return collection of user's children that are registered
     */
    public Collection<Child> getRegisteredChildren(Lunch lunch) {
        Collection<Child> registeredChildren = new HashSet<>();
        Collection<Child> usersChildren = childService.loadChildrenByParent(sessionInfoBean.getCurrentUser());
        for (Attendance attendance : lunch.getConsumers()) {
            if(usersChildren.contains(attendance.getChild())) {
                registeredChildren.add(attendance.getChild());
            }
        }
        return registeredChildren;
    }

    /**
     * Get weekday of specified day as String
     *
     * @param day
     *            to get weekday from
     * @return weekday in German
     */
    public String getWeekday(DayPlan day) {
        return day.getDayDate().getDisplayName(Calendar.DAY_OF_WEEK, Calendar.LONG, Locale.GERMAN);
    }

    public Collection<DayPlan> getNextWeek() {
        return nextWeek;
    }

    public String getLunch() {
        return lunch;
    }

    public void setLunch(String lunch) {
        this.lunch = lunch;
    }

    public Collection<String> getAttendances() {
        return attendances;
    }

    public void setAttendances(Collection<String> attendances) {
        this.attendances = attendances;
    }

    public DayPlan getDayPlan() {
        return dayPlan;
    }

    public void setDayPlan(DayPlan dayPlan) {
        if(dayPlan != null) {
            this.dayPlan = dayPlan;
        }
    }

    public void setDayPlanByTime(Calendar time) {
        dayPlan = dayPlanService.loadDayPlan(time);
    }

    public boolean isDayPlanSelected() {
        return dayPlan != null;
    }
}

src/main/java/at/qe/sepm/skeleton/ui/controllers/TaskListController.java
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.Task;
import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.services.TaskService;
import at.qe.sepm.skeleton.services.UserService;
import at.qe.sepm.skeleton.ui.beans.SessionInfoBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.Calendar;
import java.util.Collection;

/**
 * Controller for the task list view.
 *
 */
@Component
@Scope("view")
public class TaskListController {
    
    @Autowired
    private UserService userService;
    
    @Autowired
    private TaskService taskService;
    
    @Autowired
    private SessionInfoBean sessionInfoBean;
    
    private Collection<Task> allTasks;
    
    private Collection<Task> allParentTasks;
    
    private Collection<Task> filteredTasks;
    
    /**
     * Get User by id
     *
     * @param id
     *            as String
     * @return User
     */
    private User getUser(String id) {
        return userService.loadUser(id);
    }
    
    /**
     * Get all tasks of a parent
     * 
     * @param id
     *            from parent as String
     * @return Collection of tasks
     */
    public Collection<Task> getTasksOfParent(String id) {
        return taskService.loadTasksByParent(getUser(id));
    }
    
    /**
     * Get all active tasks of a parent
     * 
     * @param id
     *            of parent as String
     * @return Collection of tasks
     */
    public Collection<Task> getActiveTasksOfParent(String id) {
        return taskService.loadActiveTasksByParent(getUser(id));
    }
    
    /**
     * Get all active tasks of the logged in user
     * 
     * @return Collection of tasks
     */
    public Collection<Task> getActiveTasksOfCurrentUser() {
        if(this.allParentTasks == null)
            this.allParentTasks = getActiveTasksOfParent(sessionInfoBean.getCurrentUser().getId());
        return this.allParentTasks;
    }
    
    public void setActiveTasksOfCurrentUser(Collection<Task> tasks){
        this.allParentTasks = tasks;
    }
    
    /**
     * Get the number of active tasks of current logged in user as a string
     *
     * @return number of active tasks as string
     */
    public String getNumberOfActiveTasksOfCurrentUser() {
        return String.valueOf(getActiveTasksOfCurrentUser().size());
    }
    
    /**
     * Get all tasks of a parent that have the deadline on the given date
     * 
     * @param id
     *            of task as String
     * @param deadline
     *            as Calendar
     * @return Collection of tasks
     */
    public Collection<Task> getTasksOfParentAndDeadline(String id, Calendar deadline) {
        return taskService.loadTasksByParentAndDeadline(getUser(id), deadline);
    }
    
    /**
     * Get all uncompleted tasks
     * 
     * @return Collection of tasks
     */
    public Collection<Task> getUncompletedTasks(){
        if(this.allTasks == null)
            this.allTasks = taskService.loadUncompletedTasks();
        return this.allTasks;
    }
    
    /**
     * Sets the collection of uncompleted task in the order, which the
     * datatable defines 
     * 
     * @param tasks set by the datatable
     */
    public void setUncompletedTasks(Collection<Task> tasks){
        this.allTasks = tasks;
    }
    
    /**
     * Get all active tasks
     * 
     * @return Collection of tasks
     */
    public Collection<Task> getActiveTasks(){
        return taskService.loadActiveTasks();
    }
    
    /**
     * Method specific for the filter attribute of the dataTable to find a specific
     * task in the dataTable
     * 
     * @return Collection of filtered tasks
     */
    public Collection<Task> getFilteredTasks() {
        return filteredTasks;
    }
    
    /**
     * Method specific for the filter attribute of the dataTable to find a specific task
     * 
     * @param filteredTasks
     *            as Collection of tasks
     */
    public void setFilteredTasks(Collection<Task> filteredTasks) {
        this.filteredTasks = filteredTasks;
    }
}

src/main/webapp/parent/lunch-overview.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name="content">

        <div class="main-menu">
            <h:outputStylesheet name="css/style-parent-basic.css"/>
            <h:outputStylesheet name="css/style-employee-main.css"/>
        </div>
        <div class="page-content container">
            <h3>Mittagsessensübersicht für aktuelle Woche</h3>
            <h:form id="lunchForm">
                <div>
                    <div class="row">
                        <p:dataTable var="dayPlan" value="#{dayPlanListController.currentWeek}" widgetVar="dayTable"
                                     id="dayTable" scrollable="true" scrollHeight="600"
                                     class="dayPlanTable" emptyMessage="Keine Mahlzeiten gefunden"
                                     selectionMode="single" rowKey="#{dayPlan.id}" style="margin-top: 20px;">


                            <p:column headerText="Tag">
                                <h:outputText value="#{dayPlan.id.time}">
                                    <f:convertDateTime pattern="dd.MM.yyyy" timeZone="CET"/>
                                </h:outputText>
                            </p:column>

                            <p:column headerText="Anmeldungen">
                                <ui:repeat var="lunch" value="#{dayPlan.lunches.toArray()}">

                                    <p>#{lunch.menu} (€
                                        <h:outputText value="#{lunch.price}">
                                            <f:convertNumber type="number" pattern="#0.00"/>
                                        </h:outputText>):
                                            <ui:repeat var="child" value="#{lunchRegistrationBean.getRegisteredChildren(lunch).toArray()}">

                                                <p> #{child.firstName} #{child.lastName}</p>

                                            </ui:repeat>
                                    </p>

                                </ui:repeat>
                            </p:column>
                        </p:dataTable>
                    </div>
                </div>
            </h:form>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/parent/lunch-registration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:define name="content">

        <div class="main-menu">
            <h:outputStylesheet name="css/style-parent-basic.css"/>
            <h:outputStylesheet name="css/style-employee-main.css"/>
        </div>
        <div class="page-content container">
            <h3>Mittagsessensanmeldung für nächste Woche</h3>
            <h:form id="lunchForm">
                <div>
                    <div class="row">

                        <p:dataTable var="dayPlan" value="#{lunchRegistrationBean.nextWeek}" widgetVar="dayTable"
                                     id="dayTable" scrollable="true" scrollHeight="200"
                                     class="dayPlanTable" emptyMessage="Keine Mahlzeiten gefunden"
                                     selectionMode="single" tableStyle="table-layout: auto"
                                     selection="#{lunchRegistrationBean.dayPlan}"
                                     rowKey="#{dayPlan.id}" style="margin-top: 20px;">


                            <p:column headerText="Tag">
                                <h:outputText value="#{dayPlan.id.time}">
                                    <f:convertDateTime pattern="EEE dd.MM.yy" locale="de_DE" />
                                </h:outputText>
                            </p:column>

                            <p:column headerText="Anmeldungen">
                                <ui:repeat var="lunch" value="#{dayPlan.lunches.toArray()}">

                                    <p>#{lunch.menu} (
                                        <h:outputText value="#{lunch.price}">
                                            <f:convertNumber type="number" pattern="#0.00€"/>
                                        </h:outputText>):
                                        <ui:repeat var="child"
                                                   value="#{lunchRegistrationBean.getRegisteredChildren(lunch).toArray()}">

                                            <p> #{child.firstName} #{child.lastName}</p>

                                        </ui:repeat>
                                    </p>

                                </ui:repeat>
                            </p:column>

                            <p:ajax event="rowSelect" update="@form" process="dayTable">
                                <f:setPropertyActionListener target="#{lunchRegistrationBean.dayPlanByTime}"
                                                             value="#{dayPlan.id}"/>
                            </p:ajax>

                        </p:dataTable>
                    </div>

                    <!-- Register button -->
                    <div class="row">
                        <div class="buttons-fix">
                            <!-- Colored buttons if day is selected -->
                            <c:if id="selected" test="#{lunchRegistrationBean.dayPlanSelected}">
                                <p:commandLink id="configdata" update="@form:dayTable"
                                               oncomplete="PF('lunch-registration').show()">
                                    <div class="col-md-6 button-fix reg" id="config-action">
                                        <img src="../../resources/images/add_user-green.png" class="button-fix-icon"
                                             id="config-icon"/>
                                        <h3 class="button-register-text">ANMELDEN</h3>
                                    </div>
                                </p:commandLink>
                            </c:if>

                            <!-- Gray buttons if no day is selected -->
                            <c:if id="not-selected" test="#{!lunchRegistrationBean.dayPlanSelected}">
                                <div class="col-md-6 button-fix dereg-inactive">
                                    <img src="../../resources/images/add_user-gray.png" class="button-fix-icon"/>
                                    <h3 class="button-deregister-text-inactive">ANMELDEN</h3>
                                </div>
                            </c:if>

                            <!-- Deregister button if day is selected -->
                            <c:if id="selected" test="#{lunchRegistrationBean.dayPlanSelected}">
                                <p:commandLink id="delete-caregiver"
                                               onclick="PF('lunch-deregistration').show();">
                                    <div class="col-md-6 button-fix dereg">

                                        <img src="../../resources/images/remove_user-red.png"
                                             class="button-fix-icon"/>
                                        <h3 class="button-deregister-text">ABMELDEN</h3>
                                    </div>
                                </p:commandLink>
                            </c:if>


                            <!-- Deregister button if no day is selected -->
                            <c:if id="not-selected" test="#{!lunchRegistrationBean.dayPlanSelected}">
                                <div class="col-md-6 button-fix dereg-inactive">
                                    <img src="../../resources/images/remove_user-gray.png" class="button-fix-icon"/>
                                    <h3 class="button-deregister-text-inactive">ABMELDEN</h3>
                                </div>
                            </c:if>
                        </div>
                    </div>

                    <p:dialog header="Anmeldungen" id="lunch-registration" widgetVar="lunch-registration"
                              modal="true" showEffect="fade" hideEffect="fade" resizable="false" closeOnEscape="true">
                        <p:outputPanel id="dayPlanData" rendered="#{not empty lunchRegistrationBean.getDayPlan()}">
                            <h:panelGrid>
                                <h:selectOneMenu id="lunch" class="menu-dropdown"
                                                 value="#{lunchRegistrationBean.lunch}">
                                    <f:selectItem itemLabel="Menu auswählen"
                                                  noSelectionOption="true"></f:selectItem>
                                    <f:selectItems value="#{lunchRegistrationBean.getDayPlan().getLunches()}"
                                                   var="lunch" itemValue="#{lunch.id}"
                                                   itemLabel="#{lunch.menu} €#{lunch.price}0"/>
                                </h:selectOneMenu>
                            </h:panelGrid>
                            <p:separator/>
                            <h:panelGrid>
                                <p:selectCheckboxMenu id="children" value="#{lunchRegistrationBean.attendances}"
                                                      label="Kinder"
                                                      filter="false" panelStyle="width:250px">
                                    <f:selectItems value="#{lunchRegistrationBean.possibleChildren}"
                                                   var="attendance" itemValue="#{attendance.id}"
                                                   itemLabel="#{attendance.child.firstName} #{attendance.child.lastName}"/>
                                </p:selectCheckboxMenu>
                            </h:panelGrid>
                            <p:separator/>
                            <h:panelGrid columns="2">
                                <p:commandButton value="Speichern" action="#{lunchRegistrationBean.saveRegistration()}"
                                                 oncomplete="PF('lunch-registration').hide()"
                                                 update=":lunchForm:dayTable" class="button-save"/>

                                <p:commandButton value="Abbrechen" onclick="PF('lunch-registration').hide()" class="button-abort"/>
                            </h:panelGrid>
                        </p:outputPanel>
                    </p:dialog>

                    <!-- Dialog for lunch deregistration, called by 'Abmelden' button -->
                    <p:dialog header="Anmeldungen löschen" widgetVar="lunch-deregistration" modal="true"
                              closeOnEscape="true">
                        <p>Möchten Sie alle Essensanmeldungen für diesen Tag stornieren? </p>

                        <p:commandButton id="deregistrat" value="Abmelden" process="@this" update="@form:dayTable"
                                         onclick="PF('lunch-deregistration').hide()" icon="ui-icon-check"
                                         class="button-save">
                            <f:actionListener binding="#{lunchRegistrationBean.deleteRegistration()}"/>
                        </p:commandButton>
                        <p:commandButton value="Abbrechen" type="button" onclick="PF('lunch-deregistration').hide()"
                                         styleClass="ui-confirmdialog-no"
                                         icon="ui-icon-close" class="button-abort"/>
                    </p:dialog>

                    <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" width="300">
                        <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes"
                                         icon="ui-icon-check"/>
                        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no"
                                         icon="ui-icon-close"/>
                    </p:confirmDialog>
                </div>
            </h:form>
        </div>
    </ui:define>
</ui:composition>