src/main/java/at/qe/sepm/skeleton/model/Attendance.java
package at.qe.sepm.skeleton.model;

import java.util.UUID;
import java.util.Calendar;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.domain.Persistable;

/**
 * Entity representing attendances of children on certain days.
 * 
 */
@Entity
public class Attendance implements Persistable<String> {

	private static final long serialVersionUID = 1L;

	@Id
	private final String id;

	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Calendar creationDate;

	@Temporal(TemporalType.TIMESTAMP)
	private Calendar arrivalTime;

	@Temporal(TemporalType.TIMESTAMP)
	private Calendar departureTime;

	@ManyToOne(optional = false)
	@JoinColumn(name = "DAY_PLAN_DATE")
	private DayPlan dayPlan;

	@ManyToOne(optional = false)
	@JoinColumn(name = "CHILD_ID")
	private Child child;

	@ManyToOne
	@JoinColumn(name = "LUNCH_ID")
	private Lunch lunch;

	@ManyToOne
	@JoinColumn(name = "PERSON_ID")
	private Person pickUpPerson;

	@Column
	private boolean attending;

	public Attendance() {
		this.id = UUID.randomUUID().toString();
		attending = true;
	}

	public Attendance(DayPlan dayPlan, Child child) {
		this();
		this.dayPlan = dayPlan;
		this.child = child;
	}

	@Override
	public String getId() {
		return id;
	}

	@Override
	public boolean isNew() {
		return creationDate == null;
	}

	public Calendar getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Calendar creationDate) {
		this.creationDate = creationDate;
	}

	public Calendar getArrivalTime() {
		return arrivalTime;
	}

	public void setArrivalTime(Calendar arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	public Calendar getDepartureTime() {
		return departureTime;
	}

	public void setDepartureTime(Calendar departureTime) {
		this.departureTime = departureTime;
	}

	public DayPlan getDayPlan() {
		return dayPlan;
	}

	public void setDayPlan(DayPlan dayPlan) {
		this.dayPlan = dayPlan;
	}

	public Child getChild() {
		return child;
	}

	public void setChild(Child child) {
		this.child = child;
	}

	public Lunch getLunch() {
		return lunch;
	}

	public void setLunch(Lunch lunch) {
		this.lunch = lunch;
	}

	public Person getPickUpPerson() {
		return pickUpPerson;
	}

	public void setPickUpPerson(Person pickUpPerson) {
		this.pickUpPerson = pickUpPerson;
	}

	public boolean isAttending() {
		return attending;
	}

	public void setAttending(boolean attending) {
		this.attending = attending;
	}

	@Override
	public int hashCode() {
		int hash = 7;
		hash = 59 * hash + Objects.hashCode(this.getId());
		return hash;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Attendance)) {
			return false;
		}
		final Attendance other = (Attendance) obj;
		if (!Objects.equals(this.getId(), other.getId())) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "at.qe.sepm.skeleton.model.Attendance[ id='" + this.getId() + "']";
	}

}

src/main/java/at/qe/sepm/skeleton/model/Caregiver.java
package at.qe.sepm.skeleton.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Entity representing caregivers.
 * 
 */
@Entity
@Table(name = "PERSON")
@DiscriminatorValue("C")
public class Caregiver extends Person {

    private static final long serialVersionUID = 1L;

    @Column
    boolean confirmed;

    @ManyToMany(mappedBy = "caregivers", fetch = FetchType.EAGER)
    private Set<Child> children;

    public Caregiver() {
        super();
        this.confirmed = false;
        this.children = new HashSet<>();
    }

    public Caregiver(String firstName, String lastName) {
        super(firstName, lastName);
        this.confirmed = false;
        this.children = new HashSet<>();
    }

    public boolean isConfirmed() {
        return confirmed;
    }

    public void setConfirmed(boolean confirmed) {
        this.confirmed = confirmed;
    }

    public Set<Child> getChildren() {
        return this.children;
    }

    public void setChildren(Set<Child> children) {
        this.children = children;
    }

    public void addChild(Child child) {
        this.children.add(child);
    }

    public void addAllChildren(Set<Child> children) {
        this.children.addAll(children);
    }

    public void removeChild(Child child) {
        this.children.remove(child);
    }

    public void removeAllChildren(Set<Child> children) {
        this.children.removeAll(children);
    }

    @Override
    public String toString() {
        return "at.qe.sepm.skeleton.model.Caregiver[ id='" + this.getId() + "' name='" + super.getFirstName()
                + " " + super.getLastName() + "']";
    }

}

src/main/java/at/qe/sepm/skeleton/model/Child.java
package at.qe.sepm.skeleton.model;

import java.util.*;

import javax.persistence.*;

import org.springframework.data.domain.Persistable;

/**
 * Entity representing children.
 * 
 */
@Entity
public class Child implements Persistable<String> {

	private static final long serialVersionUID = 1L;

	@Id
	private final String id;

	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Calendar creationDate;

	@Column(nullable = false)
	private String firstName;

	@Column(nullable = false)
	private String lastName;

	@Column(nullable = false)
	@Enumerated(EnumType.STRING)
	private Gender gender;

	@Column(nullable = false)
	@Temporal(TemporalType.DATE)
	private Calendar birthdate;

	private boolean[] attendanceDays;

	private String remarks;

	@Column(nullable = false)
	@Temporal(TemporalType.DATE)
	private Calendar registrationDate;

	@Temporal(TemporalType.TIMESTAMP)
	private Calendar deregistrationDate;

	private String importantInformation;

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "CHILDREN_CAREGIVER",
			joinColumns = @JoinColumn(name = "CHILD_ID", referencedColumnName = "ID"),
			inverseJoinColumns = @JoinColumn(name = "CAREGIVER_ID", referencedColumnName = "ID"))
	private Set<Caregiver> caregivers;

	@ManyToOne
	@JoinColumn(name = "EMERGENCY_CONTACT_ID", referencedColumnName = "ID")
	private Person emergencyContact;

	@ManyToMany(mappedBy = "children", fetch = FetchType.EAGER)
	private Set<User> parents;

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "CHILD_INTERNAL_SIBLINGS",
			joinColumns = @JoinColumn(name = "CHILD_ID", referencedColumnName = "ID"),
			inverseJoinColumns = @JoinColumn(name = "SIBLING_ID", referencedColumnName = "ID"))
	private Set<Child> internalSiblings;

	@ManyToMany(mappedBy = "internalSiblings", fetch = FetchType.EAGER)
	private Set<Child> internalSiblingsOf;

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "CHILD_EXTERNAL_SIBLINGS",
			joinColumns = @JoinColumn(name = "CHILD_ID", referencedColumnName = "ID"),
			inverseJoinColumns = @JoinColumn(name = "SIBLING_ID", referencedColumnName = "ID"))
	private Set<Sibling> externalSiblings;

	boolean enabled;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "child")
	private Set<Attendance> attendances;

	public Child() {
		this.parents = new HashSet<>();
		this.caregivers = new HashSet<>();
		this.internalSiblings = new HashSet<>();
		this.internalSiblingsOf = new HashSet<>();
		this.externalSiblings = new HashSet<>();
		this.attendances = new HashSet<>();
		this.id = UUID.randomUUID().toString();
		this.enabled = true;
		this.attendanceDays = new boolean[7];
		Arrays.fill(attendanceDays, false);
	}

	public Child(String firstName, String lastName, Gender gender, Calendar birthdate, Calendar registrationDate) {
		this();
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.birthdate = birthdate;
		this.registrationDate = registrationDate;
	}

	@Override
	public String getId() {
		return this.id;
	}

	@Override
	public boolean isNew() {
		return (null == creationDate);
	}

	public Calendar getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Calendar creationDate) {
		this.creationDate = creationDate;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Gender getGender() {
		return gender;
	}

	public void setGender(Gender gender) {
		this.gender = gender;
	}

	public Calendar getBirthdate() {
		return birthdate;
	}

	public void setBirthdate(Calendar birthdate) {
		this.birthdate = birthdate;
	}

	public boolean[] getAttendanceDays() {
		return attendanceDays;
	}

	public void setAttendanceDays(boolean[] attendanceDays) {
		this.attendanceDays = attendanceDays;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Calendar getRegistrationDate() {
		return registrationDate;
	}

	public void setRegistrationDate(Calendar registrationDate) {
		this.registrationDate = registrationDate;
	}

	public Calendar getDeregistrationDate() {
		return deregistrationDate;
	}

	public void setDeregistrationDate(Calendar deregistrationDate) {
		this.deregistrationDate = deregistrationDate;
	}

	public String getImportantInformation() {
		return importantInformation;
	}

	public void setImportantInformation(String importantInformation) {
		this.importantInformation = importantInformation;
	}

	public Set<Caregiver> getCaregivers() {
		return caregivers;
	}

	public void addCaregiver(Caregiver caregiver) {
		caregivers.add(caregiver);
	}

	public void removeCaregiver(Caregiver caregiver) {
		caregivers.remove(caregiver);
	}

	public Person getEmergencyContact() {
		return emergencyContact;
	}

	public void setEmergencyContact(Person emergencyContact) {
		this.emergencyContact = emergencyContact;
	}

	public Set<User> getParents() {
		return parents;
	}

	public void addParent(User parent) {
		this.parents.add(parent);
	}

	public void removeParent(User parent) {
		this.parents.remove(parent);
	}

	public Set<Child> getInternalSiblings() {
		return internalSiblings;
	}

	public void addInternalSibling(Child internalSibling) {
		this.internalSiblings.add(internalSibling);
	}

	public void addAllInternalSibling(Set<Child> internalSiblings) {
		this.internalSiblings.addAll(internalSiblings);
	}

	public void removeInternalSibling(Child internalSibling) {
		this.internalSiblings.remove(internalSibling);
	}

	public void removeAllInternalSibling(Set<Child> internalSiblings) {
		this.internalSiblings.removeAll(internalSiblings);
	}

	public Set<Sibling> getExternalSiblings() {
		return externalSiblings;
	}

	public void addExternalSibling(Sibling externalSibling) {
		this.externalSiblings.add(externalSibling);
	}

	public void addAllExternalSibling(Set<Sibling> externalSiblings) {
		this.externalSiblings.addAll(externalSiblings);
	}

	public void removeExternalSibling(Sibling externalSibling) {
		this.externalSiblings.remove(externalSibling);
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set<Attendance> getAttendances() {
		if(attendances == null) {
			attendances = new HashSet<>();
		}
		return attendances;
	}

	public void addAttendance(Attendance attendance) {
		if(attendances == null) {
			attendances = new HashSet<>();
		}
		this.attendances.add(attendance);
	}

	public void removeAttendance(Attendance attendance) {
		if(attendances == null) {
			this.attendances = new HashSet<>();
		} else {
			this.attendances.remove(attendance);
		}
	}

	@Override
	public int hashCode() {
		int hash = 7;
		hash = 59 * hash + Objects.hashCode(this.id);
		return hash;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Child)) {
			return false;
		}
		final Child other = (Child) obj;
		if (!Objects.equals(this.id, other.id)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "at.qe.sepm.skeleton.model.Child[ id='" + this.id + "' name='"
				+ this.firstName + " " + this.lastName + "']";
	}

}

src/main/java/at/qe/sepm/skeleton/model/Gender.java
package at.qe.sepm.skeleton.model;

/**
 * Enumeration of available genders.
 * 
 */
public enum Gender {
	MALE, FEMALE, OTHER
}

src/main/java/at/qe/sepm/skeleton/model/MonthPlan.java
package at.qe.sepm.skeleton.model;

import javax.persistence.Entity;
import javax.persistence.Id;

import org.springframework.data.domain.Persistable;

/**
 * Model format for data of a certain month.
 *
 */
@Entity
public class MonthPlan implements Persistable<String> {
    
    private static final long serialVersionUID = 1L;
    
    @Id
    public int monthId;
    public String month;
    public int ovrOccupancy;
    public int avrOccupancy;
    public int open;

    public MonthPlan() {
    }
    
    public MonthPlan(int monthId, String month, int ovrOccupancy, int avrOccupancy, int open) {
        this.monthId = monthId;
        this.month = month;
        this.ovrOccupancy = ovrOccupancy;
        this.avrOccupancy = avrOccupancy;
        this.open = open;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public int getOvrOccupancy() {
        return ovrOccupancy;
    }

    public void setOvrOccupancy(int ovrOccupancy) {
        this.ovrOccupancy = ovrOccupancy;
    }

    public int getAvrOccupancy() {
        return avrOccupancy;
    }

    public void setAvrOccupancy(int avrOccupancy) {
        this.avrOccupancy = avrOccupancy;
    }

    public int getOpen() {
        return open;
    }

    public void setOpen(int open) {
        this.open = open;
    }

    @Override
    public String getId() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    @Override
    public boolean isNew() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    public int getMonthId() {
        return monthId;
    }
    
    public void setMonthId(int monthId) {
        this.monthId = monthId;
    }

}

src/main/java/at/qe/sepm/skeleton/ui/beans/SessionInfoBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.UserRole;
import at.qe.sepm.skeleton.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

/**
 * Session information bean to retrieve session-specific parameters.
 * 
 */
@Component
@Scope("session")
public class SessionInfoBean {

    @Autowired
    private UserService userService;

    /**
     * Attribute to cache the current user.
     *
     */
    private User currentUser;

    /**
     * Returns the currently logged on user, null if no user is authenticated
     * for this session.
     *
     * @return currentUser
     */
    public User getCurrentUser() {
        if (currentUser == null) {
            String currentUserName = getCurrentUserName();
            if (currentUserName.isEmpty()) {
                return null;
            }
            currentUser = userService.loadUserByEmail(currentUserName);
        }

        return currentUser;
    }

    /**
     * Returns the username of the user for this session, empty string if no
     * user has been authenticated for this session.
     *
     * @return
     */
    public String getCurrentUserName() {
        if (!isLoggedIn()) {
            return "";
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        return auth.getName();
    }

    /**
     * Returns the roles of the user for this session as space-separated list,
     * empty string if no user has been authenticated for this session-
     *
     * @return
     */
    public String getCurrentUserRoles() {
        if (!isLoggedIn()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority role : auth.getAuthorities()) {
            sb.append(role.getAuthority());
            sb.append(' ');
        }
        return sb.toString().trim();
    }

    /**
     * Checks if a user is authenticated for this session.
     *
     * @return true if a non-anonymous user has been authenticated, false
     * otherwise
     */
    public boolean isLoggedIn() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null) {
            return auth.isAuthenticated() && !auth.getName().equals("anonymousUser");
        } else {
            return false;
        }
    }

    /**
     * Checks if the user for this session has the given role (c.f.
     * {@link UserRole}).
     *
     * @param role
     *            the role to check for as string
     * @return true if a user is authenticated and the current user has the
     * given role, false otherwise
     */
    public boolean hasRole(String role) {
        if (role == null || role.isEmpty() || !isLoggedIn()) {
            return false;
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority ga : auth.getAuthorities()) {
            if (role.equals(ga.getAuthority())) {
                return true;
            }
        }
        return false;
    }

}

src/main/webapp/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/templates/main.xhtml"
>
    <ui:define name="content">
        <div class="main-menu">
            <h:outputStylesheet name="css/style-employee.main.css"/>
        </div>
        <div class="page-content container">

            <div class="item-list">
                <!-- Attendence window -->
                <div class="row">
                    <div class="col">
                        <h:form>
                            <div class="item-section col-md-4">
                                <div class="registration-background ">
                                    <div class="item-bar">
                                        <h4 class="item-bar-name">Nächster Tag</h4>
                                    </div>
                                    <div class="registration-text">
                                        <h3 class="registration-text-head">
                                            <h:outputText value="#{dayPlanDetailController.nextDayPlan.id.time}" >
                                                <f:convertDateTime pattern="EEE dd.MM.yy" locale="de_DE" />
                                            </h:outputText>
                                        </h3>
                                        <h3 class="registration-text-head">
                                            Angemeldet:
                                            <ui:repeat var="attendance"
                                                       value="#{attendanceListController.attendancesOfNextDayOfCurrentUser.toArray()}">

                                                 #{attendance.child.firstName}

                                            </ui:repeat>
                                        </h3>
                                    </div>
                                </div>
                            </div>
                        </h:form>
                    </div>

                    <!-- Missing button-->
                    <div class="col">
                        <h:form>
                            <div class="item-section col-md-4">
                                <a href="./attendance.xhtml">
                                    <div class="registration-button">
                                        <img src="../../resources/images/callsign.png"
                                             class="registration-button-icon"/>
                                        <h3 class="registration-button-text">Abwesenheit <br/> melden</h3>
                                    </div>
                                </a>
                            </div>
                        </h:form>
                    </div>


                    <!-- Person button -->
                    <div class="row">
                        <h:form>
                            <div class="item-section col-md-4">
                                <a href="./attendance.xhtml">
                                    <div class="time-button">
                                        <img src="../../resources/images/person.png" class="time-button-icon"/>
                                        <h3 class="time-button-text">Abholperson <br/> festlegen</h3>
                                    </div>
                                </a>
                            </div>
                        </h:form>


                        <!-- Time window-->
                        <h:form>
                            <div class="item-section col-md-4">
                                <div class="time-background">
                                    <div class="item-bar">
                                        <h4 class="item-bar-name">Bring/Abholzeiten</h4>
                                        <!--<a href="./home.xhtml"><img src="../../resources/images/config-icon.png" class="item-config-image" /></a>-->
                                    </div>
                                    <h3 class="bring-time-text time-text">Bringzeit:</h3> <br/>
                                    <h3 class="bring-time-value time-text">#{dayPlanDetailController.getArrivalTimeOfToday()}</h3>
                                    <h3 class="take-time-text time-text">Abholzeit:</h3><br/>
                                    <h3 class="take-time-value time-text">#{dayPlanDetailController.getDepartureTimeOfToday()}</h3>
                                </div>
                            </div>
                        </h:form>
                    </div>


                    <!-- Menu window -->
                    <div class="row">
                        <h:form>
                            <div class="item-section col-md-4">
                                <div class="menu-background">
                                    <div class="item-bar">
                                        <h4 class="item-bar-name">Essensanmeldungen:
                                            <h:outputText value="#{dayPlanDetailController.currentWeeksMonday.time}" >
                                                <f:convertDateTime pattern="dd.MM.yy" />
                                            </h:outputText> -
                                            <h:outputText value="#{dayPlanDetailController.currentWeeksSunday.time}" >
                                                <f:convertDateTime pattern="dd.MM.yy" />
                                            </h:outputText>
                                        </h4>
                                    </div>
                                    <div class="menu-text">
                                        <h3 class="menu-text-head">#{lunchListController.getThisWeeksLunchRegistrations()}</h3>
                                        <h3 class="menu-text-main">Nächste Essensanmeldungen bis
                                            <h:outputText value="#{lunchDetailController.currentLunchDeadline.time}" >
                                                <f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
                                            </h:outputText>
                                        </h3>
                                        <a href="./lunch-overview.xhtml">
                                            <div class="item-button">
                                                <h4 class="menu-small-button-text">Menü anzeigen</h4>
                                            </div>
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </h:form>

                        <!-- Menu button-->
                        <h:form>
                            <div class="item-section col-md-4">
                                <a href="./lunch-registration.xhtml">
                                    <div class="menu-button">
                                        <img src="../../resources/images/arrow.png" class="menu-button-icon"/>
                                        <h3 class="menu-button-text">Anmeldung <br/> verwalten</h3>
                                    </div>
                                </a>
                            </div>
                        </h:form>
                    </div>

                    <!-- Tasks button -->
                    <div class="row">
                        <h:form>
                            <div class="item-section col-md-4">
                                <a href="./task-settings.xhtml">
                                    <div class="task-button">
                                        <img src="../../resources/images/task.png" class="task-button-icon"/>
                                        <h3 class="task-button-text">Aufgaben <br/> anzeigen</h3>
                                    </div>
                                </a>
                            </div>
                        </h:form>


                        <!-- Tasks window-->
                        <h:form>
                            <div class="item-section col-md-4">
                                <div class="task-background">
                                    <div class="item-bar">
                                        <h4 class="item-bar-name">Offene Aufgaben</h4>
                                        <!--<a href="./home.xhtml"><img src="../../resources/images/config-icon.png" class="item-config-image" /></a>-->
                                    </div>
                                    <div class="task-text">
                                        <h3 class="task-text-main">#{taskListController.numberOfActiveTasksOfCurrentUser} Aufgaben</h3>
                                    </div>
                                </div>
                            </div>
                        </h:form>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/login.xhtml
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ng="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">

        <h:outputStylesheet name="css/style-login.css" />
            
        <h:form>
            <!--Render Menu for presentation site while logged out-->
            <h:panelGroup rendered="#{!sessionInfoBean.loggedIn}">
                
                <!-- Start of the logo/logout header-->
                <div class ="presentation-menu-bar">
                    <div class="presentation-logo">
                        <a href="/welcome.xhtml" id="logo-link">
                            <img src="../../resources/images/logo_white.png" id="logo-picture" style="max-width: 80%;"/>
                        </a>
                    </div>
                </div>
            </h:panelGroup>
        </h:form>
		
        <div id="login-space">
                <form id="login_form" action="#{request.contextPath}/login" method="post">
                    <h3 class="login-text">LOGIN</h3>                 
                    <p:inputText id="username" class="in-email" type="text" label="E-Mail Adresse" required="true" 
                                 placeholder="E-MAIL ADRESSE" style="border-radius: 0px !important;"/>
                    <p:inputText id="password" class="in-passwd" type="password" label="Passwort" required="true" 
                                 placeholder="PASSWORT" style="border-radius: 0px !important;"/>
                    <h:outputText value="Anmeldung nicht erfolgreich!
                                  Überprüfen Sie die E-Mail Adresse und das Passwort" rendered="#{not empty SPRING_SECURITY_LAST_EXCEPTION}" class="login-error"/>
                    <button type="submit" id="login-button" class="ui-button">
                        <span class="ui-button-text">anmelden</span>
                    </button>
                </form>
        </div>

    </ui:define>
</ui:composition>

src/main/webapp/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ng="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name="content">
        <h:outputStylesheet name="css/style-main.css" />
        <h:form>
                    
        <!--Render Menu for presentation site while logged out-->
        <h:panelGroup rendered="#{!sessionInfoBean.loggedIn}">
            
                <!-- Start of the logo/logout header-->
                <div class ="presentation-menu-bar">
                    <div class="presentation-logo">
                        <a href="/welcome.xhtml" id="logo-link">
                            <img src="../../resources/images/logo_white.png" id="logo-picture" style="max-width: 80%;"/>
                        </a>
                    </div>
                </div>
        </h:panelGroup>
        </h:form>
    </ui:define>
</ui:composition>